language: ruby
  rvm:
    - 2.6.0
# services:
# - postgresql
# script:
# - bundle exec rake db:create
# - bundle exec rake db:migrate
# - bundle exec rake
deploy:
  provider: heroku
  # app: instagramchallenge1
  # api_key:
  #   secure:
  #   repo: carlfjones/instagram-challenge
  #   branch: master
